### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by gottfrois** [asobti/kube-monkey#1]
Hey there,

Wanted to give a quick spin to this projet but not sure what's the way to go?
I can't find a docker image hosted on Docker Hub, is there one? Or should I build the docker image myself? If so, can you provide some guidelines?

Thanks

**Comment by asobti** [comment]
Yeah , I haven't hosted an image on Docker hub, but you should be able to build your own fairly easily. Take a look at the Building, Configuring and Deploying sections of the [Readme](https://github.com/asobti/kube-monkey/blob/master/README.md)

**Comment by gottfrois** [comment]
Thanks for the quick answer. Unfortunately the building step does not work due to bad references in the codebase:

```
$ make container
rm -f kube-monkey
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o kube-monkey
main.go:4:2: cannot find package "github.com/asobti/kube-monkey/config" in any of:
	/usr/local/Cellar/go/1.7.4_2/libexec/src/github.com/asobti/kube-monkey/config (from $GOROOT)
	/Users/gottfrois/.gocode/src/github.com/asobti/kube-monkey/config (from $GOPATH)
main.go:5:2: cannot find package "github.com/asobti/kube-monkey/kubemonkey" in any of:
	/usr/local/Cellar/go/1.7.4_2/libexec/src/github.com/asobti/kube-monkey/kubemonkey (from $GOROOT)
	/Users/gottfrois/.gocode/src/github.com/asobti/kube-monkey/kubemonkey (from $GOPATH)
make: *** [build] Error 1
```

**Comment by asobti** [comment]
Did some testing, and apparently Go isn't looking for dependencies in the right places (`vendor/`) unless you clone the project within your Go path. Could you try this:

```shell
$ go get github.com/asobti/kube-monkey
$ cd $GOPATH/src/github.com/asobti/kube-monkey
$ make container
```

**Comment by gottfrois** [comment]
looks good thx
