### ISSUE TITLE
Consider to support some other k8s controllers(rc、daemonset etc.)

### ISSUE THREAD

**Issue by YuxiJin-tobeyjin** [asobti/kube-monkey#10]
Really very good job，sir.
I‘ve made some practice in my kubernetes cluster.I found kube-monkey only kill pod under deployment.I've created some pods under rc and taged with kube-monkey tag as I used in my deployment.It seemed that kube-monkey don't have any impact on pod under rc. 
Sir，do you have a plan to support some other k8s controllers(rc、daemonset etc.) ,this will make kube-monkey much more useful.
Many tks.

**Comment by asobti** [comment]
Yeah, kube-monkey does not target RCs. I chose to go with Deployments since that is now the recommended way instead of replication controllers.

Daemonsets are a good idea. I'll look into that.

**Comment by neverfox** [comment]
So does this mean it won't work with StatefulSets?

**Comment by asobti** [comment]
Correct, it won't work with StatefulSets today. That is also a feature worth adding

**Comment by neverfox** [comment]
How hard is something like that to add? I'm not a Go master, but if it's straightforward, I could perhaps do a PR.

**Comment by Spellchaser** [comment]
Should be trivial to add now. Go nuts.

**Comment by asobti** [comment]
Closing this ticket now. We support a lot of other deployment-types now. if there is a specific one missing that you need, please file a new Issue for it.
