### ISSUE TITLE
Not able to run in debug mode

### ISSUE THREAD

**Issue by ffjjcclxxx** [asobti/kube-monkey#108]
I am trying to use the debug mode which can immediately kill the pod, but not sure what I did wrong, the immediately kill never happened.

Here is the config.yaml I have:

---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: dmp-system
  data:
    config.toml: |
      [kubemonkey]
      DryRun = false
      run_hour = 18
      start_hour = 19
      end_hour = 20
      blacklisted_namespaces = ["kube-system"]
      DebugEnabled = true
      DebugScheduleImmediateKill = true

**Comment by asobti** [comment]
The debug settings go in a separate section. your config map should look like this:

```yaml
[kubemonkey]
run_hour = 8
start_hour = 10
end_hour = 16
blacklisted_namespaces = ["kube-system"]

[debug]
enabled = true
schedule_immediate_kill = true
```

**Comment by ffjjcclxxx** [comment]
Thank you so much!
