### ISSUE TITLE
[Feature request] Attacks based on pod disruption budget

### ISSUE THREAD

**Issue by worldtiki** [asobti/kube-monkey#110]
**Proposal**
Ability to define a kill mode or kill value that is based on the pod disruption budget for that deployment.

The idea behind this is that if you define in a PDB that it's ok to have x% of max unavailability, then it should stand to reason that it's also safe for kube to kill a number of pods based on this percentage.

Example:
```
kill-mode: pdb-based
kill-value: equals
```
or
```
kill-mode: pdb-based
kill-value: +25%
```

I'm not sure how best to deal with scenarios where this kill mode is set but there is no PDB. I guess it could either do nothing, or use some default value. At this point I just wanted to gauge interest in this new feature. I may be able to contribute part of the code for this.

**Comment by asobti** [comment]
I think this makes a lot of sense. I'd like to see a new kill mode (PDB) that just kills as many pods as the PDB allows. For eg., if PDB is set at 50%, it should kill 50% of the pods.

I initially considered having kube-monkey randomly kill pods *up to* the PDB, but the problem with that is it will be quite rare that the number of pods killed exactly equals your PDB, which should be the point of this kill-mode. i.e., this kill-mode should validate that your PDB is correctly set.
