### ISSUE TITLE
kube monkey permission issue

### ISSUE THREAD

**Issue by prageethw** [asobti/kube-monkey#113]
Failed to fetch eligible deployments for namespace  due to error: deployments.apps is forbidden: User "system:serviceaccount:kube-system:default" cannot list deployments.apps at the cluster scope

**Comment by asobti** [comment]
Does this only happen when using the helm chart for deployment?

**Comment by prageethw** [comment]
closed

**Comment by richabhatia20** [comment]
@asobti I'm getting this issue when running my k8s cluster on AWS EC2. My app is running in namespace 'dev' and Kube monkey is running in namespace 'kube-system'. The configmap is in kube-system too. 

Here's the full error : 
```
Failed to fetch eligible deployments for namespace dev due to error: deployments.apps is forbidden: User "system:serviceaccount:kube-system:default" cannot list deployments.apps in the namespace "dev"
```

**Comment by prageethw** [comment]
@richabhatia20  did you use helm to install it?

**Comment by richabhatia20** [comment]
@prageethw No I just used the docker image

**Comment by prageethw** [comment]
you need to create a service account that has rights to access other namespaces and run monkey with that service account... otherwise, use helm to install as it will do the magic in the background.

**Comment by richabhatia20** [comment]
@prageethw I did create the service account as suggested on https://github.com/fnproject/fn-helm/issues/21 but it didnt help.

**Comment by prageethw** [comment]
@richabhatia20 

unfortunately, you are not running monkey with RBAC using service account?


##################
# Install Tiller #
##################

kubectl create \
    -f https://raw.githubusercontent.com/prageethw/k8s-specs/master/helm/tiller-rbac.yml \
    --record --save-config

helm init --service-account tiller

kubectl -n kube-system \
    rollout status deploy tiller-deploy

##################
# Run monkey
##################

cd kube-monkey

helm install --name my-release helm/kubemonkey
