### ISSUE TITLE
why not submit for official helm repo?

### ISSUE THREAD

**Issue by prageethw** [asobti/kube-monkey#114]
time this helm to submit as an official helm chart?

**Comment by prageethw** [comment]
@asobti  I found this better than the chaos monkey currently in helm chart repohttps://github.com/linki/chaoskube,helm , but it has an official helm chart https://github.com/helm/charts/tree/master/stable/chaoskube, what stopping submitting as candidate to official helm repo, my pr must be fixed the issues we had on current helm, so users must be able to directly just install using helm , we might need to create a better helm installation page though.

**Comment by asobti** [comment]
TBH, I have absolutely no experience with Helm as I've never used it. So that's why I've never submitted it. I might consider it after I merge your PR

**Comment by prageethw** [comment]
@asobti let me know if any helm, Happy to set-up a helm page for Kube-monkey.

**Comment by asobti** [comment]
@prageethw Thanks for all the improvements to the helm chart. Given that you probably understand the helm chart for kube-monkey the best, it would be great if you could take care of submitting it to the official helm repo.

**Comment by prageethw** [comment]
@asobti  yep leave it with me...

**Comment by prageethw** [comment]
I have submitted this to official helm. hence closing.
