### ISSUE TITLE
Failed to verify Kube ApiServer Access

### ISSUE THREAD

**Issue by Spellchaser** [asobti/kube-monkey#12]
**Problem**
Output of kubectl logs 
```
Starting kube-monkey...
--
open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
 
goroutine 1 [running]:
main.main()
/home/user/go/src/github.com/asobti/kube-monkey/main.go:24 +0x108
```
**Environment**
Trying to run kube-monkey in a kube cluster that is behind a firewall hence no auth configured. 
This error could be because I'm running v1.5.2 of kubernetes.

Is there any reason not to upgrade the kubernetes/client-go version?
```
[user@box] $ curl http://localhost:8080/api/
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "xxx.xxx.xxx.xxx:x443"
    }
  ]
}
[user@box] $ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-02-06T23:54:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"c55cf2b7d8bfeb947f77453415d775d7f71c89c2", GitTreeState:"clean", BuildDate:"2017-02-06T23:54:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Debugging**
Tracing the error goes to 
https://github.com/asobti/kube-monkey/blob/master/kubernetes/kubernetes.go#L11
which calls Google's Kubernetes APi verification at
https://github.com/asobti/kube-monkey/blob/master/vendor/k8s.io/client-go/1.5/rest/config.go#L262 

In the kubernetes docs, "/var/run/secrets/kubernetes.io/serviceaccount/token" should always be automatically generated. It's possible that this problem occurs if the service account admission controller is not enabled. Additionally "spec.serviceAccountName field has been automatically set" is not true for any deployed pods. 

Our current configuration does not generate anything in the service account. i.e.
```
[user@box ~]$ kubectl describe sa
Name:           default
Namespace:      kube-system
Labels:         <none>

Image pull secrets:     <none>

Mountable secrets:      <none>

Tokens:                 <none>
```

**Reason for Issue**
I'm primarily opening this issue 
1. if I find a fix, other people can resolve this quickly.
2. ask why not upgrade the kubernetes/client-go version

**Comment by asobti** [comment]
Hmm, interesting. I haven't seen an environment where `serviceaccount/token` is not generated. It might be possible to make unauth access a config. 

Regarding client-go upgrade - no reason not to. I just haven't had a chance to test a newer version yet.

**Comment by Spellchaser** [comment]
So this isn't an issue with kube-monkey per se, but rather with kubernete's client-go. AFAIK they're only supporting authenticated clusters. I've opened up an [issue ](https://github.com/kubernetes/client-go/issues/314) with them, but this may be avoidable depending on however client-go actually connects and talks to the kube apiserver.

For anyone curious who might also be running an unauthenticated server.

1. You must have the serviceaccount admission controller enabled. There is a recommended order found [here](https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use)
2. Use openssl genrsa (because kubernetes expects a specific format for keypairs)
``` 
sudo openssl genrsa -out /var/run/kubernetes/serviceaccount.key 1024
sudo rsa -in  /var/run/kubernetes/serviceaccount.key -pubout > /var/run/kubernetes/serviceaccount.pub
```
3. Insert the required flags which are referenced [here](https://kubernetes.io/docs/admin/service-accounts-admin/#token-controller)
```
sudo sed -i 's/KUBE_CONTROLLER_MANAGER_ARGS=""/KUBE_CONTROLLER_MANAGER_ARGS="--service-account-private-key-file=\/var\/run\/kubernetes\/serviceaccount.key"/gi' /etc/kubernetes/controller-manager
sudo sed -i 's/KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota"/KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"\nKUBE_API_ARGS="--service-account-key-file=\/var\/run\/kubernetes\/serviceaccount.pub"/gi' /etc/kubernetes/apiserver
```
4. Restart your apiserver service and controller manager at minimum
```
# Stop on all master servers
sudo -i
ls -Al /usr/lib/systemd/system/*kube* | sed -r 's/^.+\///' | xargs -L 1 -I f service "f" stop
# Restart on all three servers 
ls -Al /usr/lib/systemd/system/*kube* | sed -r 's/^.+\///' | xargs -L 1 -I f service "f" start
```

**Comment by Spellchaser** [comment]
Unfortunately after enabling service account tokens, it also expects the certificates as well...

``` 
[user@box ~]$ kubectl logs kube-monkey
Starting kube-monkey...
E1023 17:09:28.169399       1 config.go:269] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
<nil>
panic: Unable to verify client connectivity to Kubernetes server

goroutine 1 [running]:
main.main()
        /home/user/go/src/github.com/asobti/kube-monkey/main.go:24 +0x108
```

**Comment by Spellchaser** [comment]
While I was setting up km, I ran into errors that were annoying since assumptions of the configuration wasn't explicitly stated. Maybe a more experienced kubernetes admin wouldn't have problems, but I think it'd be helpful. They're kinda duhs but I guess I'm the idiot user systems need to be foolproofed for. 

1. The config map must be created before even attempting to deploy km.
2. The config map, if deployed from a file MUST be named config.toml, otherwise the file expected at /etc/kube-monkey/config.toml won't be named config.toml 
> For example: if you had saved the config as km-config.toml
> ` kubectl create configmap km-config --from-file=config.toml=km-config.toml`
3. The config map must be deployed in the same namespace. 
4. The sample config in the README hasn't included any of the new features such as the override apiserver from #6

**Comment by Spellchaser** [comment]
Aha! I think I've figure out how to make this work. 

If you're running an unauthenticated server and using cluster dns, then by disabling the InClusterConfig and pointing to the insecure API server url to the dns ip/port.

To support this very special case... it's require a bit of editing of the InClusterConfig part or handle the error. One approach was to "check" if the server was not using TLS https://github.com/kubernetes/kubernetes/pull/15230/files but this was quite contentious for the kubernetes people.

**Comment by Spellchaser** [comment]
So the custom configuration basically used the same example code from https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/doc.go 

The custom configuration was supported in client-go 1.5 as well so I imported the corresponding lib.

https://github.com/asobti/kube-monkey/pull/19

**Comment by Spellchaser** [comment]
Woo! All done
