### ISSUE TITLE
Travis job fails because check_workspace detects dirty working directory

### ISSUE THREAD

**Issue by asobti** [asobti/kube-monkey#120]
Not sure what is causing this. Double checked to confirm `go fmt` does not result in any changes.
Eg: https://travis-ci.org/asobti/kube-monkey/jobs/457331794

**Comment by asobti** [comment]
Modifed check_workspace.sh to list dirty files and it shows the following

```
$ .travis/check_workspace.sh
Dirty workspace detected. This typically indicates 'go fmt' changed some files? 
 Run 'make' locally to verify.
 M victims/victims_test.go
The command ".travis/check_workspace.sh" exited with 1
```
https://travis-ci.org/asobti/kube-monkey/jobs/457334783

but running `make gofmt` locally shows no changes to any file. Might be a version mismatch.

Temporarily disabling check_workspace.sh
https://github.com/asobti/kube-monkey/pull/122

**Comment by asobti** [comment]
This check only fails for Go 1.10.x:
https://travis-ci.org/asobti/kube-monkey/jobs/457341114

but succeeds for Go 1.11.x
https://travis-ci.org/asobti/kube-monkey/jobs/457341115

**Comment by dilyar85** [comment]
I found the problem is that `gofmt` has been updated the way formatting items of a list. 
Go 1.10 and Go 1.11 will produce different results after doing `gofmt` on the file [victims/victims_test.go](https://github.com/asobti/kube-monkey/blob/master/victims/victims_test.go#L363):
```
--- (Go-1.11)/victims/victims_test.go 
+++ (Go-1.10)/victims/victims_test.go
@@ -362,17 +362,17 @@ func TestGetDeleteOptsForPod(t *testing.T) {
 
 	tcs := []TestCase{
 		{
-			name:                   "nil pod TerminationGracePeriod",
+			name: "nil pod TerminationGracePeriod",
 			terminationGracePeriod: nil,
 			expectedGracePeriod:    defaultGracePeriod,
 		},
 		{
-			name:                   "pod TerminateGracePeriod lower than configured grace period",
+			name: "pod TerminateGracePeriod lower than configured grace period",
 			terminationGracePeriod: newInt64Pointer(*defaultGracePeriod - int64(1)),
 			expectedGracePeriod:    defaultGracePeriod,
 		},
 		{
-			name:                   "pod TerminationGracePeriod higher than configured grace period",
+			name: "pod TerminationGracePeriod higher than configured grace period",
 			terminationGracePeriod: newInt64Pointer(*defaultGracePeriod + int64(1)),
 			expectedGracePeriod:    newInt64Pointer(*defaultGracePeriod + int64(1)),
 		},
```
I suggest if we want to enforce `gofmt` via Travis CI, we should stick to exactly one version of `gofmt`.
