### ISSUE TITLE
Failing to fetch eligible deployments (deployments.apps is forbidden)

### ISSUE THREAD

**Issue by richabhatia20** [asobti/kube-monkey#130]
Using the latest docker image to deploy kube-monkey on AWS EC2 k8s cluster

My app is running in namespace 'dev' and Kube monkey is running in namespace 'kube-system'. The configmap is in kube-system too.

```
Failed to fetch eligible deployments for namespace dev due to error: deployments.apps is forbidden: User "system:serviceaccount:kube-system:default" cannot list deployments.apps in the namespace "dev"
```

Any help/pointers would be appreciated!

**Comment by richabhatia20** [comment]
As suggested at https://github.com/fnproject/fn-helm/issues/21, I did create the service account with the following steps, but it didn't help. 

```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

helm init --service-account tiller

kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
```

**Comment by rajasekhargaddam** [comment]
Hi,
We are trying to kill kubernetes pods using kubeMoney, And we are getting the similar issue, would someone help for the solution please.

Failed to fetch eligible deployments for namespace xyz-service due to error: deployments.apps is forbidden: User "system:serviceaccount:kube-system:default" cannot list deployments.apps in the namespace "xyz-service"

**Comment by richabhatia20** [comment]
@rajasekhargaddam I resolved this issue by creating a Service Account, ClusterRole and ClusterRoleBinding. You need to add the rules in ClusterRole with pods as resources and verbs: list, get, delete.

Refer to: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by nagasp** [comment]
kubectl create clusterrolebinding default-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:default

The above command seemed to solve the issue

**Comment by aluwala** [comment]
Am unable to run the above command 

clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:ns:serviceaccount" cannot create resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
