### ISSUE TITLE
Can we use kube-monkey for GCP/GKE?

### ISSUE THREAD

**Issue by narendra15** [asobti/kube-monkey#131]
Hello Team,

I have a project in GCP and have Kubernetes cluster in it where in for my testing purpose I am planning to kill my pods/nodes using kube-monkey. Can you please let me know if kube-monkey supports with GCP/GKE.

Thank you

**Comment by h-wang94** [comment]
I'm using this on a GCP GKE cluster and have confirmed this works.

If it doesn't work, you may want to check the version of Kubernetes you're running: https://github.com/kubernetes/client-go#compatibility-matrix
