### ISSUE TITLE
Redesign how grace period for pods being terminated is decided

### ISSUE THREAD

**Issue by asobti** [asobti/kube-monkey#134]
In the past, the grace period was configurable at a global level and would default to 5sec.

In 4821c5e450d8b5727bb9239a2636226e0b8d3ee0 I changed the behavior slightly to use the max of the configured grace period and the pod's termination grace period.

I'm now reconsidering this and think my change might not have been ideal. kube-monkey should not be gracefully terminating pods as that is not the type of chaos this tool is meant to generate. When pods die in a production environment unexpected, they rarely will do so gracefully.

What I'm thinking might be the right thing to do is:
1. Revert 4821c5e450d8b5727bb9239a2636226e0b8d3ee0
2. Use a globally configured grace period (as was the case before)
3. Allow individual Victims to override the grace period using a label. If the label is specified, it takes precedence over the globally configured value.

**Comment by markusjevringgoeuro** [comment]
I think this is a great idea. I was going to start working on a PR for this, but if you've already thought about it, that would be better =)

**Comment by lingrino** [comment]
@asobti It looks like this never got reverted. Would you be open to a PR that reverts the commit so that kube-monkey grace period overrides any pod specified grace period? Thanks!

**Comment by asobti** [comment]
Definitely. If you prep the PR I'd be happy to review and merge.

**Comment by lingrino** [comment]
Perfect, hoping to get that in next week. Thanks
