### ISSUE TITLE
Kube-Monkey Helm issue

### ISSUE THREAD

**Issue by Mohitg06** [asobti/kube-monkey#148]
Followed helm install --name my-release kubemonkey \
               --set config.dryRun=false \
               --set config.whitelistedNamespaces="namespace1\"\,\"namespace2\"\,\"namespace3"

But still when the chart gets deployed, it takes the default values from values.yaml.  I tried updating the values.yaml , thats when I get the issue https://github.com/asobti/kube-monkey/issues/147

**Comment by asobti** [comment]
@prageethw who wrote the helm charts

**Comment by Mohitg06** [comment]
Thanks @prageethw , can you please help

**Comment by prageethw** [comment]
Hi @mohit06 I’m on holidays will take a look when I have a chance

**Comment by Mohitg06** [comment]
@prageethw , hope you had good holidays it seems like an escape character issue., 

I tried the below configuration: helm install --name my-test2 kubemonkey --set config.dryRun=false --set config.whitelistedNamespaces="namespace1" --namespace namespace1, i dont see any terminations happening.
 I have set the runHour: 10 and startHour:11

**Comment by pragyesh15** [comment]
Hi,
I am getting following issue while deploying kube-monkey through helm chart. Any help will be appreciated.

```
F1219 05:51:46.276171       1 main.go:43] While parsing config: (6, 28): never reached
goroutine 1 [running]:
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.stacks(0xc000235600, 0xc000250000, 0x57, 0xb6)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:766 +0xd4
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).output(0x1a625c0, 0xc000000003, 0xc00003a6e0, 0x19ee092, 0x7, 0x2b, 0x0)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:717 +0x306
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).printDepth(0x1a625c0, 0x7f0700000003, 0x1, 0xc000147ee8, 0x1, 0x1)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).print(0x1a625c0, 0x3, 0xc000147ee8, 0x1, 0x1)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.Fatal(0xc000147ee8, 0x1, 0x1)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:1125 +0x53
main.initConfig()
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/main.go:43 +0xb2
main.main()
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/main.go:52 +0x39
```

**Comment by asobti** [comment]
@pragyesh15 What version are you running? Are you running the latest from master?

**Comment by pragyesh15** [comment]
Yes

**Comment by worldtiki** [comment]
A new version of the charts is now available.
