### ISSUE TITLE
Container build failing

### ISSUE THREAD

**Issue by sabdalla80** [asobti/kube-monkey#150]
L33850OUS:kube-monkey abdas1$ make container
Running docker with ''
Sending build context to Docker daemon    112MB
Step 1/3 : FROM ubuntu
 ---> d131e0fa2585
Step 2/3 : RUN if (dpkg -l | grep -cq tzdata); then         echo "tzdata package already installed! Skipping tzdata installation";     else         echo "Installing tzdata to avoid go panic caused by missing timezone data";         apt-get update && apt-get install -y --no-install-recommends 	apt-utils 		tzdata 	&& rm -rf /var/lib/apt/lists/*;     fi
 ---> Using cache
 ---> 66f65ffbac1f
Step 3/3 : COPY kube-monkey /kube-monkey
COPY failed: stat /var/lib/docker/tmp/docker-builder401660720/kube-monkey: no such file or directory
make: *** [container] Error 1

**Comment by asobti** [comment]
Currently we are not using multi-stage builds for kube-monkey. As a result, `make container` expects kube-monkey to have been compiled before hand.

Do `make && make container` to build a container.
