### ISSUE TITLE
Kube-Monkey not able to kill pods in my Azure AKS cluster

### ISSUE THREAD

**Issue by suresh447** [asobti/kube-monkey#152]
I deployed kube-monkey in my Azure Aks cluster with following config map and deployment file

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-monkey-config-map
  namespace: kube-system
data:
  config.toml: |
    [kubemonkey]
    run_hour = 4
    start_hour = 5
    end_hour = 6
    blacklisted_namespaces = ["kube-system"]
    whitelisted_namespaces = ["kubemonkey"] 

Deployment file 
# Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    kube-monkey/enabled: enabled
    kube-monkey/identifier: springboot(app name)
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
    kube-monkey/mtbf: '1'(wants to kill pods on monday)
  name: kube-monkey
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-monkey
        kube-monkey/enabled: enabled
        kube-monkey/identifier: springboot (app name)
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
        kube-monkey/mtbf: "1"(wants to kill pods on monday)
    spec:
      containers:
        -
          args:
            - "-v=5"
            - "-log_dir=/var/log/kube-monkey"
          command:
            - /kube-monkey
          image: "ayushsobti/kube-monkey:v0.3.0"
          name: kube-monkey
          volumeMounts:
            -
              mountPath: /etc/kube-monkey
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: kube-monkey-config-map

After deploying this kube-monkey i am getting below error

 kubectl logs -n kube-system kube-monkey-cfb8447bf-9ssm5
I0805 09:15:42.473457       1 config.go:82] Successfully validated configs
I0805 09:15:42.473484       1 main.go:54] Starting kube-monkey with v logging level 5 and local log directory /var/log/kube-monkey
I0805 09:15:42.535240       1 kubemonkey.go:24] Status Update: Generating next schedule at 2019-08-05 04:00:00 -0700 PDT
I0805 11:00:00.000172       1 schedule.go:64] Status Update: Generating schedule for terminations
W0805 11:00:00.017166       1 factory.go:46] Failed to fetch eligible deployments for namespace kubemonkey due to error: deployments.apps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "deployments" in API group "apps" in the namespace "kubemonkey"
I0805 11:00:00.017881       1 schedule.go:57] Status Update: 0 terminations scheduled today
I0805 11:00:00.017915       1 kubemonkey.go:62] Status Update: Waiting to run scheduled terminations.
I0805 11:00:00.017937       1 kubemonkey.go:76] Status Update: All terminations done.
I0805 11:00:00.018053       1 kubemonkey.go:24] Status Update: Generating next schedule at 2019-08-06 04:00:00 -0700 PDT
        ********** Today's schedule **********
No terminations scheduled
        ********** End of schedule **********

Can you give me any suggestions to solve this error

**Comment by asobti** [comment]
The error seems quite descriptive:
> Failed to fetch eligible deployments for namespace kubemonkey due to error: deployments.apps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "deployments" in API group "apps" in the namespace "kubemonkey"

I do not know how Azure AKS manages and handles permissions, but I'd recommend you look at that.

Closing because this isn't an issue with kube-monkey
