### ISSUE TITLE
Pods getting terminated even after scheduled end hour is completed

### ISSUE THREAD

**Issue by suresh447** [asobti/kube-monkey#154]
I have installed kube-monkey using helm chart and i tested by giving 
config:
  dryRun: false
  runHour: 4
  startHour: 5
  endHour: 6
  blacklistedNamespaces: "kube-system"
  whitelistedNamespaces:  "kubemonkey"
  timeZone: America/Chicago
  debug:
   enabled: true # if you want to enable debugging and see how pods killed immediately set enabled and schedule_immediate_kill to true
   schedule_immediate_kill: false

After running kube-monkey it is started terminating the targeted pods and after completing the end hour also the targeted pods are terminating

loadtest-7f9c8db9d5-8t5rr   1/1     Running   0          8s
loadtest-7f9c8db9d5-fvhcn   1/1     Running   0          56s

Pods are keep on terminating even after the end hour is completed.

**Comment by asobti** [comment]
In debug mode, start_hour and end_hour are not considered. This is by design.
See https://github.com/asobti/kube-monkey/blob/master/schedule/schedule.go#L85

**Comment by suresh447** [comment]
Hi Asobti/Kube-Monkey

Thanks for you immediate response.if i am not enable debug mode kube monkey
is not killing the target pods in the given start hour and end hour.is
there any specific time period we have to maintain can you please let me
know.

Thanks
Suresh
