### ISSUE TITLE
problems about docker pull and k8s helm install

### ISSUE THREAD

**Issue by lcwus2** [asobti/kube-monkey#157]
first problem is about docker pull ,like this:
xxx@xxx-desktop:~/kube-monkey/helm$ docker pull ayushsobti/kube-monkey
Using default tag: latest
Error response from daemon: manifest for ayushsobti/kube-monkey:latest not found

second problem is when I helm install release in my namespace, pod'status is  imagePullBackOff, error details are this:
Failed to pull image "ayushsobti/kube-monkey:v0.3.0": rpc error: code = Unknown desc = error pulling image configuration: G 
│ t https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/22/227592f3da2062fdb72c92cdacd53a787aab7307e99efc9f030c969e1807bca6/data?verify=1569402825-SSKhEsxrAVsCk6b55qYO0%2 
│ Gm9pg%3D: net/http: TLS handshake timeout

**Comment by lcwus2** [comment]
I don't know these problems' reasons.
hope someone can help, thanks:(

**Comment by asobti** [comment]
You might have hit an intermittent error with cloudflare/dockerhub. The command `docker pull ayushsobti/kube-monkey:v0.3.0` works for me. Closing this issue.
