### ISSUE TITLE
How to kill pods, I am getting this ??

### ISSUE THREAD

**Issue by abhinandan1989** [asobti/kube-monkey#165]
Hi ,
I am getting this after my kube-monkey deployment

Every 2.0s: kubectl logs kube-monkey-64b6b9c766-5nm5k -n kube-system                                                                 master: Mon Dec  9 06:23:42 2019

I1209 11:22:40.499217       1 config.go:74] Successfully validated configs
I1209 11:22:40.499236       1 main.go:52] Starting kube-monkey with v logging level 5 and local log directory /var/log/kube-monkey
F1209 11:23:10.500931       1 main.go:55] Unable to verify client connectivity to Kubernetes apiserver
goroutine 1 [running]:
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.stacks(0xc420038a00, 0xc4204d2000, 0x67, 0xb6)
        /Users/andrewsr/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).output(0x17dc620, 0xc400000003, 0xc4201022c0, 0x174b2e5, 0x7, 0x37, 0x0)
        /Users/andrewsr/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:717 +0x30f
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).printDepth(0x17dc620, 0x7faf00000003, 0x1, 0xc420481f48, 0x1, 0x1)
        /Users/andrewsr/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).print(0x17dc620, 0x3, 0xc420481f48, 0x1, 0x1)
        /Users/andrewsr/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.Fatal(0xc420481f48, 0x1, 0x1)
        /Users/andrewsr/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:1125 +0x53
main.main()
        /Users/andrewsr/go/src/github.com/asobti/kube-monkey/main.go:55 +0x1ea

I did the configuration for my app but after the yml file deployment 
My kube-monkey is crashing 
 billow i am sharing my all files can you please sugest me how to fix it.?

configMap.yml

---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 15
      start_hour = 16
      end_hour = 17
      blacklisted_namespaces = ["kube-system"]
      whitelisted_namespaces = ["abhi"]
      time_zone = "Asia/Kolkata"
      graceperiod_sec= 10
      [debug]
      enabled= true
      schedule_immediate_kill= true

 deployment.ymal

---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kube-monkey
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kube-monkey
    template:
      metadata:
        labels:
          app: kube-monkey
      spec:
        containers:
        - name: kube-monkey
          command:
          - "/kube-monkey"
          args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
          image: andrewsrobertamary/kube-monkey:latest
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/kube-monkey"
        volumes:
        - name: config-volume
          configMap:
            name: kube-monkey-config-map

fileuploaddeployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileupload
  namespace: abhi
  labels:
    app: fileupload
    kube-monkey/enabled: enabled
    kube-monkey/identifier: fileupload
    kube-monkey/mtbf: '1'
    kube-monkey/kill-mode: fixed
    kube-monkey/kill-value: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileupload
  template:
    metadata:
      labels:
        app: fileupload
        kube-monkey/enabled: enabled
        kube-monkey/identifier: fileupload
        kube-monkey/mtbf: '1'
        kube-monkey/kill-mode: fixed
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - name: fileupload
        image: kundan2019/docker:fileupload
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
service.ymal

apiVersion: v1
kind: Service
metadata:
  name: fileupload
  namespace: abhi
  labels:
    run: fileupload
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.56.2
  ports:
  - name: serverconsole
    port: 8080 # port of service
    protocol: TCP
    targetPort: 8080
  selector:
    app: fileupload
~
Thank you in advance

**Comment by asobti** [comment]
The error message is coming from https://github.com/asobti/kube-monkey/blob/master/kubernetes/kubernetes.go#L31.

The client is unable to talk to your apiserver. Verify you are passing in the correct parameters to connect to the cluster.
