### ISSUE TITLE
Kube monkey pod is in CrashBackLoop 

### ISSUE THREAD

**Issue by ddhoot09** [asobti/kube-monkey#167]
We are facing issue with kube monkey pod. It is crashing immediately after deployment.

Following is an error
F1219 06:47:53.450335       1 main.go:43] While parsing config: (6, 28): never reached
goroutine 1 [running]:
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.stacks(0xc00025f500, 0xc000278000, 0x57, 0xb6)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:766 +0xd4
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).output(0x1a625c0, 0xc000000003, 0xc00010e580, 0x19ee092, 0x7, 0x2b, 0x0)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:717 +0x306
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).printDepth(0x1a625c0, 0x7f7000000003, 0x1, 0xc00015dee8, 0x1, 0x1)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).print(0x1a625c0, 0x3, 0xc00015dee8, 0x1, 0x1)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.Fatal(0xc00015dee8, 0x1, 0x1)
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:1125 +0x53
main.initConfig()
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/main.go:43 +0xb2
main.main()
        /Users/asobti/Coding/go/src/github.com/asobti/kube-monkey/main.go:52 +0x39

**Comment by pragyesh15** [comment]
I am also facing the same issue and it was working till yesterday.

**Comment by ddhoot09** [comment]
We are seeing this issue from today morning

**Comment by asobti** [comment]
Any info on version/commit you are running would be helpful

**Comment by ddhoot09** [comment]
Following is the values.yaml file

**Comment by ddhoot09** [comment]
# Default values for kubemonkey.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
rbac:
  enabled: true
image:
  repository: ayushsobti/kube-monkey
  tag: v0.3.0
  pullPolicy: IfNotPresent
config:
  dryRun: false
  runHour: 8
  startHour: 10
  endHour: 16
  blacklistedNamespaces: "kube-system"
  whitelistedNamespaces: psr-data
  timeZone: Asia/Kolkata
  debug:
   enabled: false # if you want to enable debugging and see how pods killed immediately set enabled and schedule_immediate_kill to true
   schedule_immediate_kill: false
args:
  logLevel: 5
  logDir: /var/log/kube-monkey

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

**Comment by ddhoot09** [comment]
Kubernetes version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", 
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8",

**Comment by asobti** [comment]
I just tested the master branch with these configs:

```toml
[kubemonkey]
run_hour = 20
start_hour = 21
end_hour = 23
blacklisted_namespaces = ["kube-system"]
time_zone = "US/Pacific"
graceperiod_sec= 5

[debug]
enabled= true
schedule_immediate_kill= true   
```

Can you try with these configs and see if they work for you?

**Comment by javajon** [comment]
The blacklist and whitelist values must be in quotes.  toml string values must be in quotes.  The default value for blacklist defines the value without quotes therefore I get this when the chart is installed.

`F0324 04:39:39.609259       1 main.go:43] While parsing config: (6, 28): never reached`

If you look in your configmap and see unquoted values such as

`blacklisted_namespaces = [ kube-system ]`

instead of 

`blacklisted_namespaces = [ "kube-system" ]`

then you will get this error. The workaround is set the values with quotes:

```
helm install my-monkey kubemonkey \
>   --set config.dryRun=false \
>   --set config.blacklistedNamespaces="\"kube-system\"" \
>   --set config.whitelistedNamespaces="\"default\"\, \"more-apps\"" \
>   --set config.debug.enabled=true \
>   --set config.debug.schedule_immediate_kill=true
```

The fix is in helm values.yaml change:

`blacklistedNamespaces: "kube-system"`

to 

`blacklistedNamespaces: "\"kube-system\""`

Also, all the examples in the readme for the chart are missing leading \" for these values.

**Comment by worldtiki** [comment]
Closing as stale
