### ISSUE TITLE
any slack channel or fourum for Kube-monkey ?

### ISSUE THREAD

**Issue by sohailjalal** [asobti/kube-monkey#181]
Hi 
Is there a slack channel or community forum to discuss Kube monkey issues ? kube-monkey task is running, however it is not killing the sample task which is in a separate namespace. I have set debug to true and schedule_immediate_kill to true in values.yaml.  the config logs show the process is running. Apologies for a basic question
Thanks
SJ

**Comment by asobti** [comment]
There's a Slack channel - its listed in the Readme. 
I, however, no longer have the time to be active there so hopefully someone else can help you out.
