### ISSUE TITLE
pods still continues to terminate after the end_hour

### ISSUE THREAD

**Issue by infa-anisrini** [asobti/kube-monkey#195]
As per my config, i stated to terminate pods between 4PM to 5PM : 

`[kubemonkey]`
`dry_run = false`
`run_hour = 15`
`start_hour = 16`
`end_hour = 17`
`blacklisted_namespaces = [ "", ]`
`whitelisted_namespaces = [ "kube-system", "lamm", "stackrox", "istio-system", ]`
`time_zone = "America/Los_Angeles"`
`[debug]`
`enabled= true`
`schedule_immediate_kill= true`

But pods continues to terminate even beyond that time:
`I0917 02:33:26.015738       1 request.go:481] Throttling request took 197.273025ms, request:` `GET:https://172.20.0.1:443/apis/apps/v1/namespaces/istio-system/daemonsets?labelSelector=kube-monkey%2Fenabled%3Denabled`
`I0917 02:33:26.018432       1 schedule.go:57] Status Update: 1 terminations scheduled today`
`I0917 02:33:26.018448       1 schedule.go:59] v1.Deployment dashboardaddon-kubernetes-dashboard scheduled for termination at 09/16/2020 19:34:21 -0700 PDT`
`I0917 02:33:26.018472       1 kubemonkey.go:62] Status Update: Waiting to run scheduled terminations.`

Not sure if i am missing something.

**Comment by worldtiki** [comment]
Hi @infa-anisrini.

You should remove the debug block from your configuration. That will cause the pods to be killed every minute and it will ignore the `starthour` and `endhour`.

**Comment by worldtiki** [comment]
@infa-anisrini feel free to reopen this ticket if the explanation was unclear.
