### ISSUE TITLE
Missing copyright information

### ISSUE THREAD

**Issue by mhartwig** [asobti/kube-monkey#228]
There are no copyright information in the license file ([LICENSE](https://github.com/asobti/kube-monkey/blob/master/LICENSE#L189)). Please add the correct information (like [here](https://github.com/apache/logging-log4j2/blob/release-2.x/LICENSE.txt#L190)).

**Comment by worldtiki** [comment]
That's how the license file is meant to be used: https://github.com/spring-projects/spring-boot/blob/main/LICENSE.txt#L190

https://medium.com/@vladimirgorej/how-to-apply-the-apache-2-0-license-to-your-open-source-software-project-cb9f777057a2
