### ISSUE TITLE
KubeMonkey isnt killing any pods

### ISSUE THREAD

**Issue by prithakundu** [asobti/kube-monkey#229]
I have installed postgresql-ha with below command:

`helm install my-release --set-string postgresql.labels.kube-monkey/enabled=enabled,postgresql.labels.kube-monkey/identifier="postgresql-ha",postgresql.labels.kube-monkey/mtbf='1',postgresql.labels.kube-monkey/kill-mode="fixed",postgresql.labels.kube-monkey/kill-value='1' bitnami/postgresql-ha`

All postgres pods are running:
NAME                                               READY   STATUS      RESTARTS   AGE
my-release-postgresql-ha-pgpool-785769dbd7-th2rv   1/1     Running     0          2m46s
my-release-postgresql-ha-postgresql-0              1/1     Running     0          2m46s
my-release-postgresql-ha-postgresql-1              1/1     Running     2          2m46s
my-release-postgresql-ha-postgresql-2              1/1     Running     0          2m46s

installed kubemonkey with below commands to kill pod:
`helm install myrelease kubemonkey/kube-monkey --set config.dryRun=false --set config.debug.enabled=true --set config.debug.schedule_immediate_kill=true`

While checking logs it says there is no running pod of postgressql

********** Today's schedule **********
k8 Api Kind     Kind Namespace  Kind Name               Termination Time
-----------     --------------  ---------               ----------------
v1.StatefulSet  default my-release-postgresql-ha-postgresql             03/23/2022 09:30:32 -0400 EDT
********** End of schedule **********
**E0323 13:30:32.177181       1 kubemonkey.go:82] Failed to execute termination for v1.StatefulSet my-release-postgresql-ha-postgresql. Error: v1.StatefulSet my-release-postgresql-ha-postgresql has no running pods at the moment**
I0323 13:30:32.177228       1 kubemonkey.go:91] Status Update: 0 scheduled terminations left.
I0323 13:30:32.177236       1 kubemonkey.go:94] Status Update: All terminations done.

**Comment by minhjh** [comment]
Maybe you can check config Kubemonkey. In toml file dry_run is true. If true, pod will not be terminated. If false, pod will be terminated


[https://github.com/asobti/kube-monkey/blob/master/internal/pkg/config/param/param.go](https://github.com/asobti/kube-monkey/blob/master/internal/pkg/config/param/param.go)
