### ISSUE TITLE
Timezone is not working on the configmap

### ISSUE THREAD

**Issue by cfontes** [asobti/kube-monkey#23]
I am trying to set the internal timezone of the scheduler for my own like this

```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 8
      start_hour = 10
      end_hour = 16
      blacklisted_namespaces = ["kube-system"]
      timezone = "Europe/Amsterdam"
```

As I saw in the code that it is there, but it is not working...

It's always like this

`I1207 15:47:29.649440       1 kubemonkey.go:26] Generating next schedule at 2017-12-07 08:00:00 -0800 PST`

So time is in time format but the scheduler is not

Changing the default in the code and recompiling it woks so that is what I did here, but would be nice to have it documented or if it's a bug fixed.

Thanks, awesome work!

**Comment by ChristofferNicklassonLenswayGroup** [comment]
We where forced to do the same solution.

**Comment by caipre** [comment]
@cfontes @ChristofferNicklassonLenswayGroup the key is `time_zone`: https://github.com/asobti/kube-monkey/blob/de1961680b2e0d5c74947c9e14217554ef0740d2/config/param/param.go#L10-L13

**Comment by Spellchaser** [comment]
@asobti Please close this issue :)

**Comment by ChristofferNicklassonLenswayGroup** [comment]
i just pulled latest  and still it prints PST.
![skarmbild fran 2018-02-12 10-07-20](https://user-images.githubusercontent.com/33247910/36089496-8bd6437a-0fdc-11e8-8064-42deabcafbc6.png)

**Comment by sudarshntn** [comment]
The values given in this page works as I have used the Asia values from here and it worked. Just a FYI.
https://golang.org/src/time/zoneinfo_abbrs_windows.go

**Comment by asobti** [comment]
Does not appear to be an issue anymore. Closing.
