### ISSUE TITLE
CVEs in latest kube-monkey Image

### ISSUE THREAD

**Issue by hiroshui** [asobti/kube-monkey#245]
I just run a CVE scan using trivy (https://github.com/aquasecurity/trivy) to see if there are any crit or high CVEs inside kube-monkey.

There are currently 1 medium, 2 high and 1 critical CVE in at least kube-monkey v0.5.0 and v0.5.1. I add the report.

[report.txt](https://github.com/asobti/kube-monkey/files/10267079/report.txt)

Seems like all of them are solvable by an upgrade of each dependency. Would be nice if you can try to integrate the upgrades of each dependency and release a new version!

Thanks a lot :)

**Comment by akhateeb22** [comment]
Hi, I do a pull request that resolve this issue
waiting for approval and merging

**Comment by akhateeb22** [comment]
This issue need to be closed 
resolved in https://github.com/asobti/kube-monkey/pull/256
