### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by gekart** [asobti/kube-monkey#3]
Nice work. How about setting MTBF to seconds rather than days. Since currently it is an integer, you can't go below daily restarts.

You should also consider whitelisting namespaces.

Why are you setting mbtf on a label rather than in the config map?

When killing pods, it would be nice to know their replication scale to find out their kill frequency.

**Comment by asobti** [comment]
> How about setting MTBF to seconds rather than days. Since currently it is an integer, you can't go below daily restarts.

Having a termination frequency in seconds feels out of scope of the intention of this project. The idea of Kube Monkey (really, Chaos Monkey) is to simulate failure scenarios in a production environment. Having failures occur every few seconds will be counter-productive.

> You should also consider whitelisting namespaces.
Currently Kube Monkey works only on an opt-in basis so having a Whitelist has limited benefits. I do like the idea of allowing Kube monkey to function on an 'opt-out' basis as well, in which case a whitelist would definitely make a lot more sense.

> Why are you setting mbtf on a label rather than in the config map?
MTBF is configured per app (Kube deployment). Setting it via a label means that Deployment owners can set the parameters of Kube Monkey for their app without having to re-configure Kube Monkey itself. So, if I run and operate Kube Monkey in your environment for all services running in that environment, you as a service owner can independently tune the parameters for how Kube Monkey handles your app without having to go through me.

> When killing pods, it would be nice to know their replication scale to find out their kill frequency.
I'm not sure I understand you on this. Could you elaborate.

**Comment by asobti** [comment]
Closing since I haven't heard back. Feel free to re-open if you have a follow up.

**Comment by mydapp** [comment]
the schedule time is  IO128  08:00:58 but my  system date is :16:00 :58 +800
