### ISSUE TITLE
Client Connectivity

### ISSUE THREAD

**Issue by valtsi** [asobti/kube-monkey#4]
I'm currently attempting at getting kube-monkey up and running on a kubernetes cluster, and I keep getting an error stating: 

`panic: Unable to verify client connectivity to Kubernetes server`

Any ideas or suggestions on what's going wrong and how to fix it? 
Thanks.

**Comment by asobti** [comment]
Are you using a VIP in front of your API server? I've noticed this as well and I think the solution might be to allow manually specifying the location for the apiserver, and not using the one from the in-cluster config file.

**Comment by valtsi** [comment]
I did some more research & testing, and seem to have figured out a solution.

First, I changed the error check after the inClusterConfig call in [kubernetes.go](https://github.com/asobti/kube-monkey/blob/5244bc4629e086dcd26204bda9921f5388439e71/kubernetes/kubernetes.go#L9) to print the error, to try and see what exactly was failing. Examining the logs after running, I received a `panic: Get https://[cluster IP]/version: x509: cannot validate certificate for [cluster IP] because it doesn't contain any IP SANs` error.

Here, the problem was that the client was attempting to authenticate on the IP, which is invalid, as opposed to the cluster DNS, which is valid.

Examining the actual inClusterConfig function in [client-go](https://github.com/kubernetes/client-go/blob/7c07d5a2af693f43ed616271f4b04fae0e0212cc/1.5/rest/config.go#L256) revealed that the config is populated with the IP, and even has a comment saying: TODO: switch to cluster DNS.

To fix this, I manually changed the Host field of the config after the function call to match the cluster DNS, and now it correctly authenticates.

**Comment by asobti** [comment]
Yeah, I figured this would be causing it. I'm currently working on a commit to allow you to override the host field of InClusterConfig via a kube-monkey configuration. I"ll re-open this Issue for now. Thanks for digging into it.

**Comment by asobti** [comment]
@valtsi You should be able to configure kube-monkey to use a different host URL now by adding the following to the config file:

```
[kubernetes]
host="https://your-apiserver-url.com"
```

On start-up, kube-monkey will log a message indicating that the API server has been overriden.
