### ISSUE TITLE
Has anyone tried to deploy this on OpenShift?

### ISSUE THREAD

**Issue by alberttwong** [asobti/kube-monkey#40]
Just curious.....

**Comment by osmancis** [comment]
I did!

**Comment by romancin** [comment]
I have been testing this, and kube-mokey container runs well in OpenShift, but it doesn't work with OpenShift deploymentConfig, only with kubernetes deployments. If you use kubernetes deployments, you loose the ability to use image streams, lifecycle hooks and custom deployment strategies, as stated in this document:
https://docs.openshift.com/container-platform/3.11/dev_guide/deployments/kubernetes_deployments.html#dev-guide-kubernetes-deployments-support

**Comment by alberttwong** [comment]
@romancin How are you starting or loading the container in OCP?

**Comment by romancin** [comment]
I am running kube-monkey inside Openshift. If I use Kubernetes Deployments inside Openshift, kube-monkey works fine. But if you use Openshift DeploymentConfig (this is the standard mode for Openshift), kube-monkey doesn’t work.

**Comment by alberttwong** [comment]
Can you share what you did?  I take it that you're loading via yaml.   I can look at why since I'm a Red Hatter that works on OCP.

**Comment by osmancis** [comment]
@romancin Can you make sure you defined the config map? I missed it first time I ran this K Monkey

**Comment by alberttwong** [comment]
For the issue, 
```error: couldn't get deployment kube-monkey-5: replicationcontrollers "kube-monkey-5" is forbidden: User "system:serviceaccount:kube-system:deployer" cannot get replicationcontrollers in the namespace "kube-system": User "system:serviceaccount:kube-system:deployer" cannot get replicationcontrollers in project "kube-system"```

```oc -n kube-system adm policy add-role-to-user -z deployer system:deployer
oc -n kube-system adm policy add-role-to-user -z builder system:image-builder
oc -n kube-system adm policy add-role-to-group system:image-puller system:serviceaccounts:kube-system```

**Comment by alberttwong** [comment]
Answer 

```
git clone https://github.com/asobti/kube-monkey
cd examples
oc login http://someserver/ -u system:admin
oc project kube-system
oc create -f configmap.yaml
oc -n kube-system adm policy add-role-to-user -z deployer system:deployer
oc -n kube-system adm policy add-role-to-user -z builder system:image-builder
oc -n kube-system adm policy add-role-to-group system:image-puller system:serviceaccounts:kube-system
oc run kube-monkey --image=docker.io/ayushsobti/kube-monkey:v0.3.0 --command -- /kube-monkey -v=5 -log_dir=/var/log/kube-monkey
then I manually added the config file to the pod which caused another deployment. 
```

**Comment by asobti** [comment]
Fixed by #137

**Comment by alberttwong** [comment]
FYI.. this is another effort.  https://github.com/chaitanyaenr/kraken

**Comment by romancin** [comment]
Sorry, but that is not the problem, as I said, kube-monkey is working well. The problem is that kube-monkey is searching for Deployments using the kubernetes api. When you use Openshift DeploymentConfig, kubernetes Deployments are not used, so kube-monkey thinks that it doesn’t have any pods to kill. If you do a `kubectl get deployments` on a Openshift cluster when you are using DeploymentConfigs, the output is empty.

**Comment by romancin** [comment]
This seems to make chaos only on the Openshift infrasctucture and not in the application pods, so I think the purpose is different than kube-monkey. Both working together would be awesome 🙂

**Comment by alberttwong** [comment]
> Sorry, but that is not the problem, as I said, kube-monkey is working well. The problem is that kube-monkey is searching for Deployments using the kubernetes api. When you use Openshift DeploymentConfig, kubernetes Deployments are not used, so kube-monkey thinks that it doesn’t have any pods to kill. If you do a `kubectl get deployments` on a Openshift cluster when you are using DeploymentConfigs, the output is empty.

So I miss understood.   I thought you couldn't deploy kube-monkey in a DC configuration.    Unfortunately you'd have to rewrite kube-monkey so that it understood OCP DC.

**Comment by loveshjain** [comment]
@alberttwong I deployed the `kube-monkey` like you mention on my openshift, but it does not seems to be working. Its giving me 

`I0531 04:04:08.061773       1 schedule.go:57] Status Update: 0 terminations scheduled today`

When I did `kubectl get deployments` i got `No resources found.`

Any idea?
