### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by asobti** [asobti/kube-monkey#41]
Please

**Comment by camilocot** [comment]
Hi, @asobti, I would like to help to add UT, could you guide me with the packages that I should start with, any coding norms, suggestions (I am a newbie with Golang) ...?

Thanks for this wonderful tool !!

**Comment by asobti** [comment]
We're in pretty decent shape wrt to unit tests now. Tests should, obviously, continually be added, but I think this Issue has served its purpose.

Thanks to all who contributed tests.
