### ISSUE TITLE
api v1 is invalid for older k8s versions

### ISSUE THREAD

**Issue by yao-xu** [asobti/kube-monkey#70]
I got an error called `Failed to fetch eligible deployments for namespace testns-ns due to error: the server could not find the requested resource`. 
The configmap, deployment, pod and victims are all in namespace testns-ns. 

Details of logs are shown below

```
I0604 22:07:37.873927       1 config.go:74] Successfully validated configs
I0604 22:07:37.873958       1 main.go:52] Starting kube-monkey with v logging level 5 and local log directory /var/log/kube-monkey
I0604 22:07:38.157628       1 kubemonkey.go:24] Status Update: Generating next schedule at 2018-06-04 16:00:00 -0700 PDT
LM-SJC-11012475:kube-monkey yxu2$ kubectl logs kube-monkey-6bbccb7699-t5wnw --namespace=testns-ns
I0604 22:07:37.873927       1 config.go:74] Successfully validated configs
I0604 22:07:37.873958       1 main.go:52] Starting kube-monkey with v logging level 5 and local log directory /var/log/kube-monkey
I0604 22:07:38.157628       1 kubemonkey.go:24] Status Update: Generating next schedule at 2018-06-04 16:00:00 -0700 PDT
I0604 23:00:00.000173       1 schedule.go:64] Status Update: Generating schedule for terminations
W0604 23:00:00.010772       1 factory.go:45] Failed to fetch eligible deployments for namespace testns-ns due to error: the server could not find the requested resource
	********** Today's schedule **********
No terminations scheduled
	********** End of schedule **********
I0604 23:00:00.011352       1 schedule.go:57] Status Update: 0 terminations scheduled today
I0604 23:00:00.011388       1 kubemonkey.go:63] Status Update: Waiting to run scheduled terminations.
I0604 23:00:00.011394       1 kubemonkey.go:77] Status Update: All terminations done.
I0604 23:00:00.011479       1 kubemonkey.go:24] Status Update: Generating next schedule at 2018-06-05 16:00:00 -0700 PDT
```

Details of configmap is shown below

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  config.toml: |
    [kubemonkey]
    host="https://your-apiserver-url.com:apiport"
    run_hour = 16
    start_hour = 17
    end_hour = 18
    blacklisted_namespaces = ["kube-system"]
    whitelisted_namespaces = ["testns-ns"]
    time_zone = "America/Los_Angeles"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.toml":"[kubemonkey]\nrun_hour = 12\nstart_hour = 12\nend_hour = 13\nblacklisted_namespaces = [\"kube-system\"]\nwhitelisted_namespaces = [\"testns-ns\"]\ntime_zone = \"America/Los_Angeles\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"kube-monkey-config-map","namespace":"testns-ns"}}
  creationTimestamp: 2018-06-01T18:09:18Z
  name: kube-monkey-config-map
  namespace: testns-ns
  resourceVersion: "2018008066"
  selfLink: /api/v1/namespaces/testns-ns/configmaps/kube-monkey-config-map
  uid: e6f8283a-65c6-11e8-9b2c-74dbd180d2d0
```

**Comment by Spellchaser** [comment]
It's trying to contact `host="https://your-apiserver-url.com:apiport"`
That's an invalid host

**Comment by marscser** [comment]
Meet the samething on my setup, with k8s version 1.7.4
W0618 18:51:15.155671       1 factory.go:45] Failed to fetch eligible deployments for namespace default due to error: the server could not find the requested resource

**This is my config-map config:**
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: default
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 8
      start_hour = 10
      end_hour = 16
      blacklisted_namespaces = ["kube-system"]
      whitelisted_namespaces = [""]
      [debug]
      enabled = true
      schedule_delay = 60
      schedule_immediate_kill = true

**And I've add following in the victim deployment,**
    kube-monkey/enabled: enabled
    kube-monkey/mtbf: "2"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"

Not sure if it's the compatible issue with kubernetes 1.7.4?

**Comment by Spellchaser** [comment]
Can you verify that you can hit your apiserver from within your victim deployment? Something like `curl localhost:8080/apis/extensions/v1beta1/deployments` 

Also if you can post what version you're using for the deployment that would help. That's the apiversion for the victim deployment

**Comment by marscser** [comment]
@Spellchaser Thanks for the reply.

Here is the victim deployment api version.
apiVersion: extensions/v1beta1

I'm running RBAC and have add a cluster_admin role to the serviceaccount kube-monkey is using.
Also tried to use the override proxy, same error.
I0619 02:26:26.430684       1 kubernetes.go:44] API server host overriden to: https://10.96.0.1:443
W0619 02:26:26.448008       1 factory.go:45] Failed to fetch eligible deployments for namespace  due to error: the server could not find the requested resource

When do curl in victim deploy it requires certificate, not sure how to get it... could you please shed some light?

curl https://10.96.0.1:443/apis/extension>
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by marscser** [comment]
I've tried following command in kube-monkey pods and it does return the deployment.
curl -ik -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.96.0.1:443/apis/extensions/v1beta1/deployments

Not sure why the kube-monkey report the error inside the container.

**Comment by marscser** [comment]
Just find if I replace the "v1beta1" with "v1", returns exactly the same error msg.

HTTP/2 404 
content-type: application/json
content-length: 206
date: Tue, 19 Jun 2018 06:47:08 GMT

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404

And I found that in victims/factory/deployments/eligible_deployments.go, it uses AppsV1(), could it be the reason?

func EligibleDeployments(clientset kube.Interface, namespace string, filter *metav1.ListOptions) (eligVictims []victims.Victim, err error) {
--
21 | enabledVictims, err := clientset.AppsV1().Deployments(namespace).List(*filter)

**Comment by Spellchaser** [comment]
Mhm when those were merged, I was wondering if it would break any older k8s versions that still had deployments in v1beta1. Good to know it wasn't an authentication problem. I'm going to leave this open to address the issue. 

If you'd like to make PRs :) Supporting older versions is better than moving to api v1 and not using any new features.

**Comment by yao-xu** [comment]
@marscser I tried to replace v1 with v1beta1 too, and I got errors
`undefined: "k8s.io/apimachinery/pkg/apis/meta/v1beta1".ListOptions`
`undefined: "k8s.io/apimachinery/pkg/apis/meta/v1beta1".GetOptions`
Could you tell me how did you resolve these problems?

**Comment by marscser** [comment]
Don't change the meta version. Just replace the app version to v1beta1 in
deployment.go . And replace AppsV1 to AppsV1beta1 in eligible_deployment.go

**Comment by worldtiki** [comment]
Closing as stale
