### ISSUE TITLE
Support for services/replica sets

### ISSUE THREAD

**Issue by oahayder** [asobti/kube-monkey#77]
Looking at the code, it seems this only supports labelling Deployments as victims: https://github.com/asobti/kube-monkey/blob/6a1c7df307481dd9165a54b0e27d2c244b283be2/victims/factory/deployments/eligible_deployments.go#L50

Any plans to support services/replica sets? Is there a workaround if we don't use deployments?

EDIT: I thikn I can just add the label selector to pods and have it work, is that correct: https://github.com/asobti/kube-monkey/blob/b42263d09f5825a25c4bbfb74cafbbe6d4aba589/victims/victims.go#L113

**Comment by asobti** [comment]
kube-monkey currently supports Deployments and StatefulSets. Daemonsets support is still missing.

I chose not to support replica sets as Kubernetes recommends using Deployments over Replica sets

> While ReplicaSets can be used independently, today it’s mainly used by Deployments as a mechanism to orchestrate pod creation, deletion and updates. When you use Deployments you don’t have to worry about managing the ReplicaSets that they create. Deployments own and manage their ReplicaSets.

https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

As for Services, a Kubernetes service is merely a load balancing tool, and does not have any pods, so kube-monkey cannot target a service.

**Comment by oahayder** [comment]
@asobti thanks for the quick response. Love the idea with this tool.

I agree deployments are preferred however our current production env uses RS. And I would like to avoid taking on the task of migrating. This is mostly due to us deploying via spinnaker where RS are the preferred targets.

Thanks for the answer 👍
