### ISSUE TITLE
mtbf

### ISSUE THREAD

**Issue by MarkDcc** [asobti/kube-monkey#9]
Can i set kube-monkey/mtbf = "0.01",Or mtbf must with int value?

**Comment by asobti** [comment]
`mtbf` must be an integer.
https://github.com/asobti/kube-monkey/blob/master/deployments/deployments.go#L57

See https://github.com/asobti/kube-monkey/issues/3 for a discussion on it

**Comment by MarkDcc** [comment]
Thank you for you answer and thank you very much for you job.Now, we found your mtbf interval is day,and this is hard code?Or where can i find set about mtbf interval ?
