### ISSUE TITLE
Run only on specific days

### ISSUE THREAD

**Issue by shaikatz** [asobti/kube-monkey#95]
Hi,

We have low traffic on Sundays, so I would like to schedule the monkey to run only on Sunday.

There is any way to do that with the current configuration options?

**Comment by asobti** [comment]
It only runs on weekdays so it should not be running on Sundays

**Comment by asobti** [comment]
This is not currently possible I think

**Comment by Spellchaser** [comment]
I'm not sure you're following the principles of chaos. You should be doing chaos engineering when your whole team is available. Ideally you want to get the point of running it only during the day in production. 

As for that feature, it shouldn't be too hard to write. There should be wonderful golang libraries that take care of parsing schedules.

**Comment by shaikatz** [comment]
Let me surprise you.
I'm working in Israeli timezone, our working days are Sun-Thu.
Sunday is the ideal day to run chaos monkey because there is less volume from our international users. 

Maybe I'll be able to implement this feature, it might take some time to me to get to it.

Thanks!
