### ISSUE TITLE
Docker container dies when a pod uses an invalid kill type

### ISSUE THREAD

**Issue by worldtiki** [asobti/kube-monkey#96]
**Scenario**:
Kube monkey generates the following schedule for the day:
- Deployment A with kill type = _potatoes_ at 10AM
- Deployment B with kill type = _fixed_ at 11 AM

At 10 AM the first attack against Deployment A will fail with the error below, and the docker container for Kube Monkey dies.
Kubernetes restarted the container but (as expected) the attack on Deployment B did not run.

**Error log**:
`{"log":"panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2018-08-31T12:06:00.021385567Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe4c072]\n","stream":"stderr","time":"2018-08-31T12:06:00.021395074Z"}
{"log":"\n","stream":"stderr","time":"2018-08-31T12:06:00.021398393Z"}`

**Comment by worldtiki** [comment]
It would be nice if Kube Monkey was able to handle this gracefully by logging an error message but moving on to the next planned attack instead of terminating.

**Comment by asobti** [comment]
Yikes. Yeah, this is no good. There should never be a case where misconfiguration by one app can take down kube-monkey entirely.

**Comment by asobti** [comment]
Fixed by #97
